# Generated by Django 5.0.1 on 2024-06-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='About', max_length=100)),
                ('section_text', models.TextField()),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('heading', models.CharField(default='UI/UX Designer & Web Developer', max_length=100)),
                ('intro_text', models.TextField()),
                ('birthday', models.DateField()),
                ('website', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('freelance_status', models.CharField(max_length=50)),
                ('additional_text', models.TextField()),
            ],
        ),
    ]
